#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           right1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftR,         tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           liftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           left2,         tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define M_PI acos(-1.0)

//DONT YOU F***ING CHANGE IT TO IN
float wheelRadiusIN = 4;

//define functions
int getStraightGoal(float in);
int getRotationGoal(float deg);

int getStraightGoal(float in) {
//627.2 for torque
//329 for speed
		return 329*(in/(wheelRadiusIN*M_PI));
}

int getRotationGoal(float deg) {
//627.2 for torque
//329 for speed
return 329*(deg/102.9);
}

task main()
{

resetMotorEncoder(left2);
resetMotorEncoder(liftR);

//claw tension
motor(claw) = 10;

//lift up and robot starts moving
motor[liftL] = motor[liftR] = 126;
motor(right1) = motor(right2) = motor(left1) = motor(left2) = 127;
wait1Msec(1500);

// tension lift, robot still moving
motor[liftL] = motor[liftR] = 20;

//forward 44.8 inches				inches*627.2/12.5
while(abs(nMotorEncoder[left2]) < getStraightGoal(72
	))
{
	motor(right1) = motor(right2) = motor(left1) = motor(left2) = 127;
}

motor(right1) = motor(right2) = motor(left1) = motor(left2) = 0;

//lift down and claw open
motor(liftR) = motor(liftL) = -10;
wait(1.0);
motor(claw) = -10;

}
